// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google";
// import { Analytics } from "@vercel/analytics/next"
import "./globals.css"
import { Sidebar } from "@/components/ui/sidebar"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: "ADAM",
  description: "Rethink your decision-making",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  return (
    <html lang="en">
      <body className={`font-sans ${geistMono.variable} ${geistMono.variable}`}>
        <div className="flex h-screen w-full overflow-hidden">
          <Suspense fallback={<div>Loading...</div>}>
            <Sidebar />
            <main className="flex-1 overflow-hidden">{children}</main>
          </Suspense>
        </div>
        <Analytics />
      </body>
    </html>
  )
}
